# Working with Factors


## Manually recode/change a factor's levels

Use `forcats::fct_recode()`

```{r chapter_5}
diamonds=diamonds %>% as_tibble()

diamonds$cut=fct_recode(diamonds$cut, "meh"="Fair", "Wow"="Premium")

summary(diamonds$cut)
```

## Collapse factor levels

fct_collapse(dataset$variable,
			NewLevelA=c("OldLevel1","Oldlevel2"),
			NewLevelB=c("OldLevel3"))
			
```{r}
print("temp")
```


## Add levels to a factor

use `fct_expand()`

```{r}
print("temp")
```


## Drop unused levels

Use `fct_drop()`
```{r}
print("temp")
```


## Change the order of a factor's levels

```{r chapter_5_end}

example_data=tribble(~person, ~condition,
                     "bob", "25 years",
                     "jane", "5 years",
                     "jim", "5 years",
                     "john", "25 years")

example_data$condition=factor(example_data$condition)

str(example_data$condition)

example_data$condition =fct_relevel(example_data$condition, c("5 years", "25 years"))

str(example_data$condition)
```



