# Making Tables with flextable

NOTES:
- **j** refers to the column
- **i** refers to the row number


## APA Table Components



## Indent values
https://davidgohel.github.io/flextable/reference/padding.html
https://stackoverflow.com/questions/64134725/indentation-in-the-first-column-of-a-flextable-object

Use the `padding` function:
```{r chapter_8, eval=FALSE}
ft <- padding(ft, i=2, j=1, padding.left=20)
```


## Add a Horizontal border (AKA horizontal "spanner")

```{r 8.2, eval=FALSE}
hline(., i=4, j=1:2, part = "body")
```


## Change font and font size

```{r 8.3, eval=FALSE}
  glm_table<-flextable::font(glm_table, part = "all", fontname = "Times") %>% # Font
                        fontsize(., size = 11, part = "all") # Font size
```

## Grouped table

```{r chapter_8_end, eval=FALSE}

cars=rownames_to_column(mtcars, var = "Model")
test=flextable::as_grouped_data(x=cars, groups = c("cyl"))
```



## Complete Example

```{r}

flextable::set_flextable_defaults(font.family = "Times New Roman", font.size = 11)

mtcars |> 
  slice(1:5) |> 
  flextable() |>
  # SET HEADER
    add_header_lines(values = "Car Stuff") |> 
    hline_top(border = fp_border_default(width = 0), part = "header") |> 
    flextable::align(align = "left", part = "header", i=1) |> 
    italic(part = "header", i=1)
```


